export const truth_string = [
  "What is the most embarrassing thing you've ever done?",
  "Have you ever lied to your best friend? If yes, about what?",
  "What is your biggest fear?",
  "Who was your first crush?",
  "Have you ever cheated on a test?",
  "What is one thing you would change about yourself?",
  "What is your most embarrassing memory?",
  "Have you ever kept a secret from your parents?",
  "What is the worst thing you've ever said to someone?",
  "What is the biggest mistake you've ever made?",
  "Have you ever stolen something?",
  "What is a guilty pleasure you have?",
  "Have you ever pretended to be sick to skip school or work?",
  "What is the meanest thing you've ever done to someone?",
  "Who do you have a secret crush on?",
  "Have you ever spread a rumor about someone?",
  "What is the weirdest thing you’ve ever done in public?",
  "What is something you've done that no one knows about?",
  "What is your biggest insecurity?",
  "Have you ever been rejected by someone you liked?",
  "What is the most childish thing you still do?",
  "What is the most trouble you've ever gotten into?",
  "What is one thing you’ve done that you regret?",
  "Have you ever been caught lying?",
  "What is the longest you've gone without showering?",
  "What is the most annoying habit you have?",
  "Have you ever snooped through someone else's phone or belongings?",
  "What is your biggest secret?",
  "Have you ever been jealous of a friend? Why?",
  "What is the worst gift you've ever received?",
  "Have you ever told someone you loved them when you didn’t mean it?",
  "What is the weirdest dream you've ever had?",
  "What is the most awkward date you've ever been on?",
  "Have you ever laughed at something inappropriate?",
  "What is one thing you’re afraid to tell your parents?",
  "What is the most disgusting thing you've ever done?",
  "Have you ever been caught cheating on anything?",
  "What is the most expensive thing you've ever stolen?",
  "What is a secret you’ve never told anyone?",
  "Have you ever accidentally insulted someone?",
  "What is the worst lie you've ever told?",
  "Have you ever been in love with someone who didn’t love you back?",
  "What is the strangest thing you’ve ever eaten?",
  "What is the most embarrassing thing you've said in front of a crush?",
  "Have you ever broken a law?",
  "What is the most awkward thing you've ever done?",
  "What is the silliest thing you're afraid of?",
  "What is your most embarrassing social media post?",
  "Have you ever lied to get out of a commitment?",
  "What is the worst thing you've ever done while drunk?",
  "Have you ever sabotaged someone on purpose?",
  "What is the weirdest rumor you’ve ever heard about yourself?",
  "Have you ever been caught doing something you shouldn’t have?",
  "What is the worst thing you’ve ever overheard about yourself?",
  "What is the most embarrassing text you've ever sent?",
  "Have you ever lied about your age?",
  "What is your most embarrassing nickname?",
  "What is the dumbest thing you’ve ever lied about?",
  "What is the most cringe-worthy thing you've ever done?"
];

export const dare_string = [
  "Dance like no one is watching for one minute.",
  "Send a text to the last person you texted saying 'I have a secret crush on you.'",
  "Try to lick your elbow.",
  "Do 20 push-ups in a row.",
  "Imitate a celebrity until someone guesses who you are.",
  "Post an embarrassing photo on social media.",
  "Do your best impression of someone in the room.",
  "Speak in an accent for the next 5 minutes.",
  "Let someone draw on your face with a marker.",
  "Wear socks on your hands for the next 10 minutes.",
  "Call a random contact in your phone and sing 'Happy Birthday' to them.",
  "Do your best chicken dance outside on the lawn.",
  "Walk backwards for the next 3 minutes.",
  "Pretend to be a waiter/waitress and take snack orders from everyone.",
  "Imitate your favorite animal for one minute.",
  "Eat a spoonful of mustard or hot sauce.",
  "Do your best dance moves for one minute.",
  "Let someone write a word on your forehead with a marker.",
  "Post a funny status on social media.",
  "Try to juggle 3 items for one minute.",
  "Speak in rhymes until your next turn.",
  "Try to touch your toes for 30 seconds without bending your knees.",
  "Let someone else pick a funny outfit for you to wear.",
  "Pretend to be a waiter and take snack orders from everyone.",
  "Do an impression of a baby being born.",
  "Do 30 jumping jacks without stopping.",
  "Pretend to be a statue for 5 minutes.",
  "Wear your clothes inside out for the rest of the game.",
  "Do an impression of a famous cartoon character.",
  "Walk around the room with a spoon on your nose.",
  "Talk in a high-pitched voice for the next 10 minutes.",
  "Let someone do your makeup.",
  "Pretend to be a waiter and take snack orders from everyone.",
  "Let someone else post something on your social media.",
  "Imitate a baby for one minute.",
  "Sing the chorus of a song loudly.",
  "Do 10 burpees in a row.",
  "Send a message to a random person in your contacts saying, 'I need your help!'",
  "Call someone and talk in a funny voice for the entire conversation.",
  "Do your best impression of a robot for one minute.",
  "Try to touch your nose with your tongue.",
  "Talk in a different language (real or made-up) for the next 5 minutes.",
  "Make up a song and sing it to the group.",
  "Do an impression of a famous movie character.",
  "Pretend to be a waiter/waitress and take snack orders from everyone.",
  "Let someone post something silly on your social media.",
  "Sing everything you say for the next 5 minutes.",
  "Do your best dance moves for one minute.",
  "Pretend to be a famous rock star for the next 5 minutes.",
  "Let someone give you a new hairstyle.",
  "Do 20 sit-ups without stopping.",
  "Try to make everyone laugh by telling a funny joke or story.",
  "Imitate a famous singer for one minute.",
  "Let someone else choose an embarrassing outfit for you to wear.",
  "Do your best impression of a supermodel on a runway.",
  "Talk like a pirate for the next 5 minutes.",
  "Pretend to be a cat for the next 5 minutes.",
  "Imitate a famous sports player for one minute.",
  "Try to touch your toes without bending your knees.",
  "Do your best impression of a robot for one minute."
];
